### PR TITLE
index.xsl

### PR DESCRIPTION
**Pull request by briesenberg07**
Wrote temp_index.xsl to accomplish [uwlswd > index.html to-dos](https://docs.google.com/document/d/13OK-OqBnqaihnfByu-wZa65F0AlpVTrUYHWZs2SZAUk/edit#bookmark=id.or1stcbufv6f), but did not do this the way I said I'd do (I did something easier 😅...). 
- Created an XML instance with category/resource groups to iterate through, used a key to fetch DOIs and descriptions from DataCite metadata.
- Added very basic list of links at top for navigation
- Updated some top-of-page text, etc.

Just something basic until #62 is resolved. Following this a new/updated index.xsl can match on `schema:disambiguatingDescription` values.

### CODE REVIEW

**Comment by cspayne** [comment]
This also looks good! I like the addition of a menu at the top. 
I wonder if there is a way to make the separation between resources and their related links and descriptions clearer. 
Maybe using a list?
I am fine with merging this, but I did see that you deleted the original index.xsl - do we want to adjust the formatting there as well and save it for when we are ready to use the BMPs? Or just go ahead and delete it and make adjustments to temp_index.xsl when we are ready?

**Comment by briesenberg07** [comment]
Thank you @cspayne !

> I wonder if there is a way to make the separation between resources and their related links and descriptions clearer. Maybe using a list? 

I agree this would be good. Right now it all just sort of looks like one big list, with the resource titles, IRIs, and descriptions as list items on the same level of hierarchy.  

I just tried a list but didn't like the way it looked (also, for some reason, my `xsl:if` wasn't working correctly and I was getting second bullets where there was no description...) What about just indenting the IRI + (if one exists) description? Is there an easy way to do this, or something similar that is used for other CAMS pages that we could use here too?

> I am fine with merging this, but I did see that you deleted the original index.xsl - do we want to adjust the formatting there as well and save it for when we are ready to use the BMPs? Or just go ahead and delete it and make adjustments to temp_index.xsl when we are ready?

I [linked to the current version of index.xsl](https://github.com/uwlib-cams/uwlswd/issues/62#issuecomment-1777737333) in #62 , so I think it's okay to get rid of it for now.

**Comment by cspayne** [comment]
> I just tried a list but didn't like the way it looked (also, for some reason, my `xsl:if` wasn't working correctly and I was getting second bullets where there was no description...) What about just indenting the IRI + (if one exists) description? Is there an easy way to do this, or something similar that is used for other CAMS pages that we could use here too?

Yes! I just added a class to those p elements and added a css indent to the index_pages.css - if that looks okay to you, I can push it before we merge.
index_indents

 
> I [linked to the current version of index.xsl](https://github.com/uwlib-cams/uwlswd/issues/62#issuecomment-1777737333) in #62 , so I think it's okay to get rid of it for now.

Perfect!

**Comment by briesenberg07** [comment]
This looks great to me! Please do push and merge (I guess here and in webviews)--thank you!

**Pull request merged**
